apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: node-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: jenkins-app-container
          image: ahmedabdelsalam19/jn-node
          ports:
            - name: httpport
              containerPort: 3000