apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jn-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jn-dep
  template:
    metadata:
      labels:
        app: jn-dep
    spec:
      # securityContext for Jenkins pod to be able to write to the local persistent volume.
      securityContext:  
            fsGroup: 1000 
            runAsUser: 1000
      serviceAccountName: jenkins-user
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport  
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home  
      volumes:
        - name: jenkins-vol
          persistentVolumeClaim:
              claimName: jenkins-pvc